force-app/main/default/objects/SLR_obj_externalPost__c/SLR_obj_externalPost__c.object-meta.xml
<CustomObject>
    <label>POST externo</label>
    <nameField>
        <label>POST externo Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>POSTS externos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SLR_obj_externalPost__c/fields/SLR_fld_body__c.field-meta.xml
<CustomField>
    <fullName>SLR_fld_body__c</fullName>
    <label>Body</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SLR_obj_externalPost__c/fields/SLR_fld_externalId__c.field-meta.xml
<CustomField>
    <fullName>SLR_fld_externalId__c</fullName>
    <label>Id externo</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SLR_obj_externalPost__c/fields/SLR_fld_title__c.field-meta.xml
<CustomField>
    <fullName>SLR_fld_title__c</fullName>
    <label>Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SLR_obj_externalPost__c/fields/SLR_fld_userId__c.field-meta.xml
<CustomField>
    <fullName>SLR_fld_userId__c</fullName>
    <label>User Id</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ExternalPostService.cls
public with sharing class ExternalPostService {
    public static void fetchAndStorePosts(){
        HttpRequest req = new HttpRequest();
        req.setEndpoint('callout:JSONPlaceholder/posts');
        req.setMethod('GET');
        req.setHeader('Content-Type', 'application/json');

        Http http = new Http();
        HttpResponse res;

        try{
            res = http.send(req);
            if(res.getStatusCode() == 200){
                List<ExternalPostWrapper> posts = 
                    (List<ExternalPostWrapper>)JSON.deserialize(
                        res.getBody(), 
                        List<ExternalPostWrapper>.class
                    );
                
                List<SLR_obj_externalPost__c> recordsToInsert = new List<SLR_obj_externalPost__c>();
                for(ExternalPostWrapper post : posts){
                    SLR_obj_externalPost__c record = new SLR_obj_externalPost__c();
                    record.SLR_fld_title__c = post.title;
                    record.SLR_fld_body__c = post.body;
                    record.SLR_fld_userId__c = post.userId;
                    record.SLR_fld_externalId__c = post.id;

                    recordsToInsert.add(record);
                }

                insert recordsToInsert;
                System.debug('Posts inserted successfully');

            } else {
                System.debug('ERROR STATUS: ' + res.getStatusCode());
            }

        } catch(Exception e) {
            System.debug('EXCEPTION: ' + e.getMessage());
        }

    }        
}